name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Android SDK
      run: |
        echo y | sdkmanager "platform-tools" >/dev/null
        echo y | sdkmanager "platforms;android-26" >/dev/null
        echo y | sdkmanager "build-tools;26.0.3" >/dev/null

    - name: Build and test
      run: ./gradlew build connectedCheck
